tasks:
  - name: remove-label
    on:
      issue_comment:
        types: [created]
      issues:
        types: [opened, edited]
    config:
      label: needs-reply
      exclude-labeler: true
  - name: add-platform-labels
    on:
      issues:
        types: [opened, edited]
  - name: add-contributors
    on: push
    config:
      base: master
      commitMsg: 'chore(readme): add new contributor'
  - name: comment-on-label
    on:
      issues:
        types: [labeled]
      pull_request:
        types: [labeled]
    config:
      base: master
      commitMsg: 'chore(readme): add new contributor'
