tasks:
  - name: remove-label
    event: issue_comment/created
    config:
      label: needs-reply
      exclude-labeler: false
  - name: add-platform-labels
    event: issues/opened
  - name: add-contributors
    event: push
    config:
      base: master
