name: Capacitor Bot

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/bot@e4ae225
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GIT_AUTHOR_NAME: Github Action
          GIT_AUTHOR_EMAIL: github-action@users.noreply.github.com
          GIT_COMMITTER_NAME: Github Action
          GIT_COMMITTER_EMAIL: github-action@users.noreply.github.com
