name: Capacitor Bot

on:
  issues:
    types:
      - opened
      - edited

jobs:
  bot:
    name: ${{ github.event_name }} ${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/capacitor-bot@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
