name: Capacitor Bot

on:
  issues:
    types:
      - opened
      - edited

jobs:
  name: ${{ github.event_name }}
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: ionic-team/capacitor-bot@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
