name: Capacitor Bot

on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  bot:
    name: ${{ github.event_name }}/${{ github.event.action }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ionic-team/bot@0e59fe03a5e38e730bee84bec921fdce1e6fbfa3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GIT_AUTHOR_NAME: Github Action
          GIT_AUTHOR_EMAIL: github-action@users.noreply.github.com
          GIT_COMMITTER_NAME: Github Action
          GIT_COMMITTER_EMAIL: github-action@users.noreply.github.com
