name: Needs Reply

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Needs Reply
        uses: dwieeb/needs-reply@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
