name: Remove Needs Reply

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Needs Reply
        id: remove_needs_reply
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/:repository/issues/:issue/labels/:label
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          label: needs-reply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ fromJson(steps.remove_needs_reply.outputs) }}
