name: Add Comment when Issue is Labeled

on:
  issues:
    types: [labeled]

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: POST /repos/:repository/issues/:issue_number/comments
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          body: |
            Hello World!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
