name: Add comment when issue is labeled

on:
  issues:
    types: [labeled]

jobs:
  do:
    name: Add comment when issue is labeled
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        if: ${{ github.event.label.name == 'bug' }}
        continue-on-error: true
        with:
          route: POST /repos/:repository/issues/:issue_number/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: |
            Hello World!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
