name: Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dwieeb/git-push@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
