name: Blah

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: echo "$FILES"
        env:
          FILES: ${{ fromJson(steps.files.outputs.all }}
