name: Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Job
    runs-on: windows-latest
    steps:
      - run: echo $Env:Path
      - run: choco install windows-sdk-10.0
      - run: cd 'C:\Program Files (x86)\Windows Kits' ; tree
