name: Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Job
    runs-on: windows-latest
    steps:
      - run: echo $Env:Path
      - run: Get-ChildItem -Path 'C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10' -Include signtool.exe -Recurse
