name: Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make changes
        run: echo hello2 > hello.txt
      - name: Commit changes
        run: |
          git config --local user.name "Daniel Imhoff"
          git config --local user.email "dwieeb@gmail.com"
          git add .
          git commit -m "Do the thing!"
      - uses: dwieeb/git-push@releases/v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
