name: Blah

on: [push, pull_request]

jobs:
  job1:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: gradle --version
      - run: which gradle
