name: Blah

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      changed-plugins: ${{ steps['changed-plugins'].outputs['changed-plugins'] }}
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: echo "$FILES"
        env:
          FILES: ${{ toJson(steps.files.outputs.all) }}
      - id: changed-plugins
        run: echo "::set-output name=changed-plugins::$(echo ${{ toJson(steps.files.outputs.all) }} | jq -cM 'map(split("/")) | map(.[0])')"
  job2:
    needs:
      - job1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: echo "$NEEDS_CONTEXT"
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
      - run: echo "$CHANGED_PLUGINS"
        env:
          CHANGED_PLUGINS: ${{ toJson(needs.job1.outputs['changed-plugins']) }}
