name: Blah

on: push

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set the value
        id: step_one
        run: echo "::set-output name=FOO::BAR"
      - name: Use it
        run: echo ${{ steps.step_one.outputs.FOO }}
      - run: echo "::set-output name=test::testing"
      - run: echo "::set-output name=plugins::$(jq -cM .packages asdf.json)"
  echo:
    needs: set-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: echo ${{ toJson(needs['set-matrix'].outputs) }}
  # build:
  #   needs: set-matrix
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     matrix:
  #       plugin: ${{ fromJson(needs['set-matrix'].outputs.plugins) }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: echo ${{ matrix.plugin }}
