name: Blah

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: gradle --version
      - run: which gradle
