name: Blah

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: dwieeb/get-changed-files@5a87587
        with:
          format: 'json'
