name: Blah

on: push

jobs:
  bot:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        xcode:
          - /Applications/Xcode_11.6_beta.app
          - /Applications/Xcode_11.5.app
    steps:
      - run: sudo xcode-select --switch ${{ matrix.xcode }}
      - run: xcodebuild -version
