name: Blah

on: push

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=plugins::$(jq -cM .packages asdf.json)"
  build:
    needs: set-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        plugin: ${{ fromJson(needs['set-matrix'].outputs.plugins) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.plugin }}
